APS.Cronicos.UI.Web/ViewModels/PrimeiroAcessoViewModel.cs
using APS.Cronicos.ViewModels.Seguranca;

namespace APS.Cronicos.UI.Web.ViewModels
{
    public class PrimeiroAcessoViewModel
    {
        public int Id { get; set; }
        public string NmUsuario { get; set; }
        public string EmailPrincipal { get; set; }
        public string EmailSecundario { get; set; }
        public string Cpf { get; set; }
        public string Token { get; set; }
        public bool FlPrimeiroAcesso { get; set; }
        public int Cnes { get; set; }

        public UnidadeViewModel Unidade { get; set; }
        public GrupoViewModel Grupo { get; set; }
        public string Senha { get; set; }
        public string SenhaConfirmada { get; set; }
    }
}

APS.Cronicos.UI.Web/Controllers/PrimeiroAcessoController.cs
using APS.Cronicos.Dominio.Helpers;
using APS.Cronicos.Dominio.Seguranca.Repositories.Interfaces;
using APS.Cronicos.UI.Web.ViewModels;
using APS.Cronicos.ViewModels.Seguranca;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using System;

namespace APS.Cronicos.UI.Web.Controllers
{
    public class PrimeiroAcessoController : BaseController
    {
        private readonly IPrimeiroAcessoRepository _primeiroAcessoRepository;
        public PrimeiroAcessoController(
            IConfiguration configuration,
            IPrimeiroAcessoRepository primeiroAcessoRepository
        ) : base(configuration)
        {
            _primeiroAcessoRepository = primeiroAcessoRepository;
        }

        [HttpGet]
        [Authorize]
        public IActionResult Index()
        {
            PrimeiroAcessoViewModel oPrimeiroAcessoVM = null;

            try
            {
                oPrimeiroAcessoVM = _mapper.Map<UsuarioViewModel, PrimeiroAcessoViewModel>(Usuario);
            }
            catch (Exception ex)
            {
                ExibirMensagem(ex.Message, TipoMensagem.Erro);
            }

            return View(oPrimeiroAcessoVM);
        }

        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public IActionResult Index(PrimeiroAcessoViewModel primeiroAcesso)
        {
            try
            {
                string senhaCriptografada = SHA256Helper.Encrypt(primeiroAcesso.Senha, ChavePublica);
                string senhaConfirmadaCriptografada = SHA256Helper.Encrypt(primeiroAcesso.SenhaConfirmada, ChavePublica);

                _primeiroAcessoRepository.TrocarSenha(primeiroAcesso.Token, primeiroAcesso.Id, primeiroAcesso.EmailPrincipal, primeiroAcesso.EmailSecundario, senhaCriptografada, senhaConfirmadaCriptografada, IdSistema);

                ExibirMensagem("Troca de senha realizada com sucesso!", TipoMensagem.Sucesso);

                return RedirectToAction("Index", "Autenticar", new { area = "Logout" });
            }
            catch (Exception ex)
            {
                ExibirMensagem(ex.Message, TipoMensagem.Erro);
                return View(primeiroAcesso);

            }
        }
    }
}

APS.Cronicos.UI.Web/Views/PrimeiroAcesso/Index.cshtml
@model APS.Cronicos.UI.Web.ViewModels.PrimeiroAcessoViewModel

@{
    ViewData["Title"] = "Primeiro Acesso";
    Layout = "~/Views/Shared/_TemplateSeguranca.cshtml";
}

<style type="text/css">
    .cpf {
        font-size: 17px;
    }
</style>

<div class="row">
    <div class="col-sm-10 col-sm-offset-1">
        <div class="login-container">
            <div class="center">
                <h3>
                    <img src="~/assets/images/Logo_APS_Branco.png" alt="">
                    <span class="white" id="nmSistema"></span>
                </h3>
            </div>
            <div class="space-6"></div>
            <div class="position-relative">
                <div id="signup-box" class="signup-box widget-box no-border visible">
                    <div class="widget-body">
                        <div class="widget-main">
                            <h4 class="header green lighter bigger">
                                <i class="ace-icon fa fa-users blue"></i>
                                Primeiro Acesso
                            </h4>

                            <div class="space-6"></div>
                            <p> Para sua segurança, altere sua senha </p>

                            @using (Html.BeginForm("Index", "PrimeiroAcesso", null, FormMethod.Post, true, new { @class = "form", id = "frmPrimeiroAcesso" }))
                            {
                                @Html.AntiForgeryToken()

                                @Html.HiddenFor(p => p.Id)
                                @Html.HiddenFor(p => p.Token)
                                @Html.HiddenFor(p => p.Cpf)

                                <fieldset>
                                    <label class="block clearfix">
                                        <span class="block input-icon input-icon-right">
                                            @Html.LabelFor(p => p.Cpf, Model.Cpf, new { @class = "form-control cpf" })
                                            <i class="ace-icon fa fa-credit-card-alt"></i>
                                        </span>
                                    </label>

                                    <label class="block clearfix">
                                        <span class="block input-icon input-icon-right">
                                            @Html.TextBoxFor(p => p.NmUsuario, new { @class = "form-control", placeholder = "Informe o nome do usuário", required = "required" })
                                            <i class="ace-icon fa fa-user"></i>
                                        </span>
                                    </label>

                                    <label class="block clearfix">
                                        <span class="block input-icon input-icon-right">
                                            @Html.TextBoxFor(p => p.EmailPrincipal, new { @class = "form-control", placeholder = "Informe o e-mail principal", required = "required", type = "email" })
                                            <i class="ace-icon fa fa-envelope-o"></i>
                                        </span>
                                    </label>

                                    <label class="block clearfix">
                                        <span class="block input-icon input-icon-right">
                                            @Html.TextBoxFor(p => p.EmailSecundario, new { @class = "form-control", placeholder = "Informe o e-mail secundário", type = "email" })
                                            <i class="ace-icon fa fa-envelope-o"></i>
                                        </span>
                                    </label>

                                    <label class="block clearfix">
                                        <span class="block input-icon input-icon-right">
                                            @Html.PasswordFor(p => p.Senha, new { @class = "form-control", placeholder = "Informe uma nova senha", required = "required" })
                                            <i class="ace-icon fa fa-key"></i>
                                        </span>
                                    </label>

                                    <label class="block clearfix">
                                        <span class="block input-icon input-icon-right">
                                            @Html.PasswordFor(p => p.SenhaConfirmada, new { @class = "form-control", placeholder = "Confirme a nova senha", required = "required" })
                                            <i class="ace-icon fa fa-key"></i>
                                        </span>
                                    </label>

                                    <div class="space-24"></div>

                                    <div class="clearfix">
                                        <button type="submit" class="width-45 pull-right btn btn-sm btn-success">
                                            <i class="ace-icon fa fa-save"></i>
                                            <span class="bigger-110">Alterar Senha</span>
                                        </button>
                                    </div>
                                </fieldset>
                            }
                        </div>

                        <div class="toolbar center">
                            @Html.ActionLink("Voltar ao Login", "Index", "Autenticar", new { area = "Login" }, new { @class = "back-to-login-link" })
                        </div>
                    </div><!-- /.widget-body -->
                </div><!-- /.signup-box -->
            </div><!-- /.position-relative -->
        </div>
    </div><!-- /.col -->
</div><!-- /.row -->