APS.Cronicos.UI.Web/ViewModels/NovaSenhaViewModel.cs
namespace APS.Cronicos.UI.Web.ViewModels
{
    public class NovaSenhaViewModel
    {
        public string Token { get; set; }
        public string Cpf { get; set; }
        public string NovaSenha { get; set; }
        public string NovaSenhaConfirmada { get; set; }
    }
}

APS.Cronicos.UI.Web/ViewModels/TrocarSenhaViewModel.cs
namespace APS.Cronicos.UI.Web.ViewModels
{
    public class TrocarSenhaViewModel
    {
        public string Cpf { get; set; }
    }
}

APS.Cronicos.UI.Web/Controllers/TrocarSenhaController.cs
using APS.Cronicos.Dominio.Seguranca.Repositories.Interfaces;
using APS.Cronicos.UI.Web.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using System;

namespace APS.Cronicos.UI.Web.Controllers
{
    [Route("[controller]")]
    public class TrocarSenhaController : BaseController
    {
        private readonly ITrocarSenhaRepository _trocarSenhaRepository;

        public TrocarSenhaController(IConfiguration configuration, ITrocarSenhaRepository trocarSenhaRepository) : base(configuration)
        {
            _trocarSenhaRepository = trocarSenhaRepository;
        }

        [AllowAnonymous]
        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }

        [AllowAnonymous]
        [HttpPost]
        [AutoValidateAntiforgeryToken]
        public IActionResult Index(TrocarSenhaViewModel trocarSenha)
        {
            try
            {
                string link = $"{HttpContext.Request.Scheme}://{HttpContext.Request.Host}/TrocarSenha/NovaSenha";

                string mensagem = _trocarSenhaRepository.TrocarSenha(trocarSenha.Cpf, link, IdSistema);

                ExibirMensagem(mensagem, TipoMensagem.Informacao);
                return RedirectToAction("Index", "Autenticar", new { area = "Login" });
            }
            catch (Exception ex)
            {
                ExibirMensagem(ex.Message, TipoMensagem.Erro);
                return View(trocarSenha);
            }
        }

        [Route("NovaSenha/{cpf}/{hash}")]
        [AllowAnonymous]
        [HttpGet]
        public IActionResult NovaSenha(string cpf, string hash)
        {
            return View(new NovaSenhaViewModel
            {
                Cpf = cpf,
                Token = hash
            });
        }

        [Route("SalvarSenha")]
        [AllowAnonymous]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult SalvarSenha(NovaSenhaViewModel senha)
        {
            try
            {
                string mensagem = _trocarSenhaRepository.NovaSenha(senha.Cpf, senha.Token, senha.NovaSenha, senha.NovaSenhaConfirmada, IdSistema);

                ExibirMensagem(mensagem, TipoMensagem.Sucesso);
                return RedirectToAction("Index", "Autenticar", new { area = "Login" });
            }
            catch (Exception ex)
            {
                ExibirMensagem(ex.Message, TipoMensagem.Erro);
                return RedirectToAction("NovaSenha", new { cpf = senha.Cpf, hash = senha.Token });
            }
        }
    }
}

APS.Cronicos.UI.Web/Views/TrocarSenha/Index.cshtml
@model APS.Cronicos.UI.Web.ViewModels.TrocarSenhaViewModel

@{
    Layout = "~/Views/Shared/_TemplateSeguranca.cshtml";
}

<div class="row">
    <div class="col-sm-10 col-sm-offset-1">
        <div class="login-container">
            <div class="center">
                <h3>
                    <img src="~/assets/images/Logo_APS_Branco.png" alt="">
                    <span class="white" id="nmSistema"></span>
                </h3>
            </div>

            <div class="space-6"></div>

            <div class="position-relative">
                <div id="login-box" class="forgot-box visible widget-box no-border">
                    <div class="widget-body">
                        <div class="widget-main">
                            <h4 class="header red lighter bigger">
                                <i class="ace-icon fa fa-key"></i>
                                Esqueci minha senha <br />
                            </h4>

                            <div class="space-6"></div>
                            <p class="text-center">
                                Informe seu CPF para receber as instruções no e-mail cadastrado
                            </p>

                            @using (Html.BeginForm("Index", "TrocarSenha", FormMethod.Post, new { @class = "form", area = "Login" }))
                            {
                                @Html.AntiForgeryToken()
                                @Html.ValidationSummary()

                                <fieldset>
                                    <label class="block clearfix">
                                        <span class="block input-icon input-icon-right">
                                            @Html.TextBoxFor(p => p.Cpf, new { @class = "form-control", placeholder = "Informe o número do CPF", @required = "required" })
                                            <i class="ace-icon fa fa-envelope"></i>
                                        </span>
                                    </label>

                                    <div class="clearfix">
                                        <button type="submit" class="width-35 pull-right btn btn-sm btn-danger">
                                            <i class="ace-icon fa fa-envelope-o"></i>
                                            <span class="bigger-110">Enviar</span>
                                        </button>
                                    </div>
                                </fieldset>
                            }
                        </div><!-- /.widget-main -->

                        <div class="toolbar center">
                            @Html.ActionLink("Voltar ao Login", "Index", "Autenticar", null, new { area = "Login", @class = "back-to-login-link" })
                        </div>
                    </div><!-- /.widget-body -->

                </div><!-- /.login-box -->

            </div><!-- /.position-relative -->
        </div>
    </div><!-- /.col -->
</div><!-- /.row -->

APS.Cronicos.UI.Web/Views/TrocarSenha/NovaSenha.cshtml
@model APS.Cronicos.UI.Web.ViewModels.NovaSenhaViewModel

@{
    ViewData["Title"] = "Nova Senha";
    Layout = "~/Views/Shared/_TemplateSeguranca.cshtml";
}

<div class="row">
    <div class="col-sm-10 col-sm-offset-1">
        <div class="login-container">
            <div class="center">
                <h3>
                    <img src="~/assets/images/Logo_APS_Branco.png" alt="">                    
                    <span class="white" id="nmSistema"></span>
                </h3>
            </div>
            <div class="space-6"></div>
            <div class="position-relative">
                <div id="signup-box" class="signup-box widget-box no-border visible">
                    <div class="widget-body">
                        <div class="widget-main">
                            <h4 class="header green lighter bigger">
                                <i class="ace-icon fa fa-users blue"></i>
                                Nova Senha
                            </h4>

                            <div class="space-6"></div>
                            <p> Você está a apenas um passo de gerar sua nova senha </p>

                            @using (Html.BeginForm("SalvarSenha", "TrocarSenha", FormMethod.Post, new { @class = "form", area = "Login" }))
                            {
                                @Html.AntiForgeryToken()

                                @Html.HiddenFor(p => p.Cpf)
                                @Html.HiddenFor(p => p.Token)

                                @Html.ValidationSummary()

                                <fieldset>
                                    <label class="block clearfix">
                                        <span class="block input-icon input-icon-right">
                                            @Html.PasswordFor(p => p.NovaSenha, new { @class = "form-control", placeholder = "Informe a nova senha", @required = "required" })
                                            <i class="ace-icon fa fa-key"></i>
                                        </span>
                                    </label>

                                    <label class="block clearfix">
                                        <span class="block input-icon input-icon-right">
                                            @Html.PasswordFor(p => p.NovaSenhaConfirmada, new { @class = "form-control", placeholder = "Confirme a nova senha", @required = "required" })
                                            <i class="ace-icon fa fa-key"></i>
                                        </span>
                                    </label>

                                    <div class="space-24"></div>

                                    <div class="clearfix">
                                        <button type="submit" class="width-45 pull-right btn btn-sm btn-success">
                                            <i class="ace-icon fa fa-save"></i>
                                            <span class="bigger-110">Alterar Senha</span>
                                        </button>
                                    </div>
                                </fieldset>
                            }
                        </div>

                        <div class="toolbar center">
                            @Html.ActionLink("Voltar ao Login", "Index", "Autenticar", new { area = "Login" }, new { @class = "back-to-login-link" })
                        </div>
                    </div><!-- /.widget-body -->
                </div><!-- /.signup-box -->
            </div><!-- /.position-relative -->
        </div>
    </div><!-- /.col -->
</div><!-- /.row -->